// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vaslxlyuajkizaoqwwad.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZhc2x4bHl1YWpraXphb3F3d2FkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5ODk4MjYsImV4cCI6MjA3MDU2NTgyNn0.jBC3lk2Gl3HpBevxNfc8EszQ2KEAilv9zOJ13ORYhN0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});